import "./globals.css"
import { Header } from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import { CartProvider } from "@/components/context/CartContext";
import { AuthProvider } from "@/components/context/AuthContext";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <div className="min-h-screen flex flex-col pb-16">
            <Header/>
              <main className="flex-grow">
                {children}
              </main>
            <Footer/>
            </div>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
